name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Use your preferred version
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docker/requirements.txt
        pip install pytest pytest-cov
    
    - name: Run unit tests
      env:
        ANALYTICS_CLIENT_ID: ${{ secrets.ANALYTICS_CLIENT_ID }}
        ANALYTICS_CLIENT_SECRET: ${{ secrets.ANALYTICS_CLIENT_SECRET }}
        ANALYTICS_REFRESH_TOKEN: ${{ secrets.ANALYTICS_REFRESH_TOKEN }}
        ANALYTICS_ORG_ID: ${{ secrets.ANALYTICS_ORG_ID }}
        ANALYTICS_MCP_DATA_DIR: ${{ secrets.ANALYTICS_MCP_DATA_DIR }}
        ACCOUNTS_SERVER_URL: ${{ secrets.ACCOUNTS_SERVER_URL }}
        ANALYTICS_SERVER_URL: ${{ secrets.ANALYTICS_SERVER_URL }}
      run: |
        pytest docker/src/tests/ --cov=tools.data_tools --cov-report=xml
    
    - name: Upload coverage
      uses: codecov/codecov-action@v3